version: '3.4'

services:

    app_database:
        image: postgres:latest
        container_name: app_db
        environment:
          - POSTGRES_USER=auctionapp_db_user
          - POSTGRES_PASSWORD=gKe6Kxk7TQkoVGYveZXLrE0hBsKsKTVH
          - POSTGRES_DB=dpg-cqhmlqaju9rs738nput0-a
        ports:
          - 5432:5433

        restart: always
 
    aunctionappmvc:
        image: ${DOCKER_REGISTRY-}aunctionappmvc
        build:
          context: .
          dockerfile: AunctionAppMVC/Dockerfile

        depends_on:
            - "app_database"
        environment: 
             - ConnectionStrings:DefaultConnection="Host=dpg-cqhmlqaju9rs738nput0-a;Database=auctionapp_db;Username=auctionapp_db_user;Password=gKe6Kxk7TQkoVGYveZXLrE0hBsKsKTVH;Port=5432;"
             - ASPNETCORE_URLS=http://+80